import {ILocalStorageKeyConfig} from "../interfaces";

export const LOCALSTORAGE_KEY: ILocalStorageKeyConfig = {
  userInfo: 'userInfo',
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MTgwNzY5NTIsImV4cCI6MTcxODA3ODE2MiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.2eOCv37VHX1jjBkOixYdJLaizxM_Hf5Z1IDlYrvDKf4'
};
